language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang
  
addons:
  apt:
    packages:
      - texinfo
      - check

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install check; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sed 's/check_pic/check/g' tests/Makefile.am | sed 's/-lrt//g' > tests/Makefile.am.tmp; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mv tests/Makefile.am.tmp tests/Makefile.am; fi
  - mkdir m4
  - export ACLOCAL_PATH=/usr/local/share/aclocal
  - autoreconf -i
  - ./configure
  - make
  - make check
  
after_failure:
  - cat tests/test-suite.log
  - find . -iname "*.log" -print
