language: c
sudo: required

os:
  - linux
  - osx

compiler:
  - gcc
  - clang
  
addons:
  apt:
    packages:
      - texinfo

script:
  - git clone https://github.com/libcheck/check.git 
  - cd check 
  - autoreconf -i -v -f
  - ./configure
  - make -j24
  - sudo make install
  - sudo ldconfig
  - cd ..
  - mkdir m4
  - export ACLOCAL_PATH=/usr/local/share/aclocal
  - autoreconf -i
  - ./configure
  - make
  - make check
  
after_failure:
  - cat tests/test-suite.log
  - find . -iname "*.log" -print
