language: c
before_script:
- sudo apt-get update
- sudo apt-get build-dep check
# provides necessary `makeinfo`
- sudo apt-get install texinfo check
# `make check` doesn't need to be executed because `check` already uses travis-ci.org
- git clone https://github.com/libcheck/check.git && cd check && autoreconf -i -v -f && ./configure && make -j24 && sudo make install && sudo ldconfig && cd ..
script:
# work around `autoconf` bug:
- mkdir m4
- export ACLOCAL_PATH=/usr/local/share/aclocal
- autoreconf -i -v -f
- ./configure
- make
- make check
after_failure:
- cat tests/test-suite.log
