language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang
  
addons:
  apt:
    packages:
      - texinfo
      - check

before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install check; fi

script:
  - mkdir m4
  - export ACLOCAL_PATH=/usr/local/share/aclocal
  - autoreconf -i
  - ./configure
  - make
  - make check
